apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud-events
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/goeasycare/nextcloud-scenarios
    targetRevision: nextcloud-argo
    path: sample/events
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud-workflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/goeasycare/nextcloud-scenarios
    targetRevision: nextcloud-argo
    path: sample/workflow
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
