apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github-release
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  github:
    nextcloud-release:
      owner: goeasycare
      repository: nextcloud-scenarios
      # TODO: Configure a webhook in GitHub pointing to this EventSource URL
      # The webhook should trigger on 'release' events.
      webhook:
        endpoint: "/release"
        port: "12000"
        method: "POST"
        url: "TODO_EXTERNAL_URL_TO_THIS_EVENTSOURCE"
      # TODO: Create a k8s secret named 'github-access' with key 'secret' containing your webhook secret
      webhookSecret:
        name: github-access
        key: secret
      events:
        - "release"
      # If repository is private, you might need an API token
      # apiToken:
      #   name: github-access
      #   key: token
