apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github-event-source
  namespace: argocd
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  github:
    # 1. Listen for COMMITS (for in-cluster sync)
    push-listener:
      owner: "goeasycare"
      repository: "nextcloud-scenarios"
      events:
        - "push"
      webhook:
        endpoint: "/push"
        port: "12000"
        method: "POST"
        url: "https://events.goeasycare.app/push"
      webhookSecret:
        name: github-access
        key: secret
      insecure: false
      active: true
      contentType: "json"
      
    # 2. Listen for RELEASES (for remote-cluster builds)
    release-listener:
      owner: "goeasycare"
      repository: "nextcloud-scenarios"
      events:
        - "release"
      webhook:
        endpoint: "/release"
        port: "12000"
        method: "POST"
        url: "https://events.goeasycare.app/release"
      webhookSecret:
        name: github-access
        key: secret
      insecure: false
      active: true
      contentType: "json"
