apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: nextcloud-build-push
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: git-tag
      - name: git-repo
  templates:
    - name: main
      inputs:
        parameters:
          - name: git-tag
          - name: git-repo
      steps:
        - - name: build-and-push
            template: build-and-publish
            arguments:
              parameters:
                - name: git-tag
                  value: "{{inputs.parameters.git-tag}}"
                - name: git-repo
                  value: "{{inputs.parameters.git-repo}}"
        - - name: update-manifests
            template: update-gitops-repo
            arguments:
              parameters:
                - name: git-tag
                  value: "{{inputs.parameters.git-tag}}"
                - name: git-repo
                  value: "{{inputs.parameters.git-repo}}"

    - name: build-and-publish
      inputs:
        parameters:
          - name: git-tag
          - name: git-repo
      container:
        image: gcr.io/kaniko-project/executor:latest
        args:
          # Context is the root of the repo
          - "--context={{inputs.parameters.git-repo}}#refs/tags/{{inputs.parameters.git-tag}}"
          # Dockerfile is located in sample/build/
          - "--dockerfile=sample/build/Dockerfile"
          # Configured for ghcr.io/goeasycare/nextcloud-custom
          - "--destination=ghcr.io/goeasycare/nextcloud-custom:{{inputs.parameters.git-tag}}"
          - "--destination=ghcr.io/goeasycare/nextcloud-custom:latest"
        volumeMounts:
          - name: docker-config
            mountPath: /kaniko/.docker/
      volumes:
        - name: docker-config
          secret:
            # Using existing secret 'ghcr-creds' found in argo-nextc-stuff
            secretName: ghcr-creds
            items:
              - key: .dockerconfigjson
                path: config.json

    - name: update-gitops-repo
      inputs:
        parameters:
          - name: git-tag
          - name: git-repo
      script:
        image: alpine/git:latest
        command: [sh]
        source: |
          set -e

          # Install kustomize
          apk add --no-cache curl
          curl -s \
            "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" \
            | sh
          mv kustomize /usr/local/bin/

          # Configure git
          git config --global user.email "argoworkflow@example.com"
          git config --global user.name "Argo Workflow"

          # Clone the repository
          REPO_URL="{{inputs.parameters.git-repo}}"
          git clone "$REPO_URL" /work
          cd /work

          # Update the kustomization.yaml with the new image tag
          cd sample/app
          kustomize edit set image \
            ghcr.io/goeasycare/nextcloud-custom=ghcr.io/goeasycare/nextcloud-custom:{{inputs.parameters.git-tag}}

          # Commit and push changes
          git add kustomization.yaml
          git commit -m \
            "Update Nextcloud image to tag {{inputs.parameters.git-tag}}"
          git push origin main
        volumeMounts:
          - name: git-credentials
            mountPath: /root/.git-credentials
            subPath: .git-credentials
          - name: git-credentials
            mountPath: /root/.gitconfig
            subPath: .gitconfig
      volumes:
        - name: git-credentials
          secret:
            # Secret should contain .git-credentials and .gitconfig files
            # with GitHub authentication configured
            secretName: git-creds
